//---------------------------------------------------------------------
// <autogenerated>
//
//     Generated by Message Compiler (mc.exe)
//
//     Copyright (c) Microsoft Corporation. All Rights Reserved.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//---------------------------------------------------------------------




namespace NameSpace
{
using System;
using System.Collections.Generic;
using System.Text;
using System.Diagnostics;
using System.Diagnostics.Eventing;
using Microsoft.Win32;
using System.Runtime.InteropServices;
using System.Security.Principal;

    public static class WEC_EVENTS_Basic
    {
        //
        // Provider Corp-WEC-Basic Event Count 0
        //

        internal static EventProviderVersionTwo m_provider = new EventProviderVersionTwo(new Guid("cf27f07f-7013-483a-bc74-97a0f6aa32fc"));
        //
        // Task :  eventGUIDs
        //

        //
        // Event Descriptors
        //


        static WEC_EVENTS_Basic()
        {
            unchecked
            {
            }
        }

    }

    public static class WEC_EVENTS_Advanced
    {
        //
        // Provider Corp-WEC-Advanced Event Count 0
        //

        internal static EventProviderVersionTwo m_provider = new EventProviderVersionTwo(new Guid("0014355c-d05c-4b81-9c93-1f6a3907e535"));
        //
        // Task :  eventGUIDs
        //

        //
        // Event Descriptors
        //


        static WEC_EVENTS_Advanced()
        {
            unchecked
            {
            }
        }

    }

    internal class EventProviderVersionTwo : EventProvider
    {
         internal EventProviderVersionTwo(Guid id)
                : base(id)
         {}


        [StructLayout(LayoutKind.Explicit, Size = 16)]
        private struct EventData
        {
            [FieldOffset(0)]
            internal UInt64 DataPointer;
            [FieldOffset(8)]
            internal uint Size;
            [FieldOffset(12)]
            internal int Reserved;
        }

    }

}
